-- CreateEnum
CREATE TYPE "Course" AS ENUM ('MANAGEMENT', 'ACCOUNTING', 'ADVERTISING_AND_PUBLICITY', 'SYSTEM_DEVELOPMENT', 'ACCOUNTING_SCIENCE', 'COMPUTER_SCIENCE', 'PUBLIC_RELATIONS', 'INTERNATIONAL_RELATIONS', 'SECRETARIAT');

-- CreateTable
CREATE TABLE "students" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "course" "Course" NOT NULL,
    "age" INTEGER NOT NULL,

    CONSTRAINT "students_pkey" PRIMARY KEY ("id")
);
